version: '3'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.3.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - elevate_net
    logging:
      driver: none
  kafka:
    image: 'confluentinc/cp-kafka:7.3.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - elevate_net
    logging:
      driver: none
  mongo:
    image: 'mongo:4.1.4'
    restart: 'always'
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - '27017:27017'
    networks:
      - elevate_net
    volumes:
      - mongo-data:/data/db
      - logs:/var/log/mongodb
  redis:
    image: 'redis:7.0.0'
    restart: 'always'
    expose:
      - '6379'
    networks:
      - elevate_net
    logging:
      driver: none
  user:
    image: shikshalokamqa/elevate-user:2.2
    ports:
      - '3001:3001'
    command: ['nodemon', 'app.js']
    environment:
      - MONGODB_URL=mongodb://mongo:27017/elevate-user
      - KAFKA_URL=kafka:9092
    depends_on:
      - kafka
      - mongo
      - redis
    networks:
      - elevate_net
    env_file:
      - ${users_env}
  notification:
    image: shikshalokamqa/elevate-notification:2.2
    ports:
      - '3002:3002'
    command: ['nodemon', 'app.js']
    environment:
      - KAFKA_HOST=kafka:9092
    depends_on:
      - kafka
    networks:
      - elevate_net
    env_file:
      - ${notification_env}
  scheduler:
    image: shikshalokamqa/elevate-scheduler:2.2
    ports:
      - '4000:4000'
    command: ['nodemon', 'app.js']
    environment:
      - KAFKA_URL=kafka:9092
      - MONGODB_URL=mongodb://mongo:27017/elevate-scheduler
    env_file:
      - ${scheduler_env}
    depends_on:
      - kafka
      - mongo
    networks:
      - elevate_net
  samiksha:
    image: shikshalokamqa/elevate-samiksha-service:0.0.1
    ports:
      - '4301:4301'
    command: ['nodemon', 'dev']
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    env_file:
      - ${samiksha_env}
    depends_on:
      - mongo
    networks:
      - elevate_net
networks:
  elevate_net:
volumes:
  mongo-data:
  logs:
