version: '3'
services:
  mongo:
    image: 'mongo:4.1.4'
    restart: 'always'
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - '27017:27017'
    networks:
      - elevate_net
    volumes:
      - mongo-data:/data/db
      - logs:/var/log/mongodb
  user:
    image: shikshalokamqa/elevate-user:2.2
    ports:
      - '3001:3001'
    command: ['nodemon', 'app.js']
    environment:
      - MONGODB_URL=mongodb://mongo:27017/elevate-user
    depends_on:
      - mongo
    networks:
      - elevate_net
    env_file:
      - ${users_env}
  notification:
    image: shikshalokamqa/elevate-notification:2.2
    ports:
      - '3002:3002'
    command: ['nodemon', 'app.js']
    networks:
      - elevate_net
    env_file:
      - ${notification_env}
  scheduler:
    image: shikshalokamqa/elevate-scheduler:2.2
    ports:
      - '4000:4000'
    command: ['nodemon', 'app.js']
    environment:
      - MONGODB_URL=mongodb://mongo:27017/elevate-scheduler
    env_file:
      - ${scheduler_env}
    depends_on:
      - mongo
    networks:
      - elevate_net
  samiksha:
    image: hishanky/samiksha:0.0.4
    ports:
      - '4301:4301'
    command: ['nodemon', 'app.js']
    environment:
      - MONGODB_URL=mongodb://mongo:27017/c4gt-samiksha
    env_file:
      - ${samiksha_env}
    depends_on:
      - mongo
    networks:
      - elevate_net
networks:
  elevate_net:
volumes:
  mongo-data:
  logs:
